### ISSUE TITLE
Function to write to log file

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsUtil#15]
faoswsUtil should be for all non-API SWS things.

One thing that is needed is helper functions to write log files. 

Functions are needed to:
- [ ] Initiate the log
- [ ] Write output to the log of _specific code chunks_ (either using `sink` or writing objects directly)
- [ ] Apply timestamps to each line of output

**Comment by mkao006** [comment]
faoswsUtil can depend on the API, the listed functions should be in the [faoswsModules](https://github.com/SWS-Methodology/faoswsModules) which is not faosws API dependent.

**Comment by sebastian-c** [comment]
Writing to the log would need to be done in the module itself, not in the `CheckDebug` chunk. This means it would have to run on the server. It could be done, but we'd lose the idea about not installing it on the server as a check.

**Comment by mkao006** [comment]
I guess it depends on how the log is written, if it simply uses `sink`, then the function itself wouldn't need to be dependent on the faosws package.

If it needs to depend on the faosws package, then put it in the faoswsUtil package.

**Comment by sebastian-c** [comment]
This isn't necessary anymore as the general log has timestamps.
