### ISSUE TITLE
computeYield out of sync with faoswsProduction

### ISSUE THREAD

**Issue by joshbrowning2358** [SWS-Methodology/faoswsUtil#2]
faoswsProduction uses a different computeYield, but they're both doing approximately the same thing.  We should synchronize these two functions so that they both function.  The main difficulty will be in the function signature, but we should be able to resolve this by assigning default arguments and checking that all the arguments we need exist.

**Comment by mkao006** [comment]
resolved de02a971668a2dca6bb219d378ab0f59bee10410
