### ISSUE TITLE
CPC 2.1 for faoswsUtil

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsUtil#22]
`cpc2fcl` and the reverse need a way to use the new CPC 2.1. I suggest a parameter to choose the CPC version which redirects to a different table. Should this be the default?

**Comment by marcosmilzo** [comment]
Concerning the trade, I would say yes. Do not know regarding the other modules.

**Comment by sebastian-c** [comment]
The new table exists: `fcl2cpc_ver_2_1`

**Comment by sebastian-c** [comment]
I propose the following:
`fcl2cpc(x, version = "2.1")`

**Comment by marcosmilzo** [comment]
Agree.

**Comment by sebastian-c** [comment]
In addition, I propose that we keep the default as the old version for a month. This will give time for people to move any important scripts. After that, we change the default to 2.1

**Comment by marcosmilzo** [comment]
This commit d57a9b94e12199ce7b156142e0567c0ecfa53c2e should close the issue. Waiting @sebastian-c  to confirm it is working on the SWS.
