### ISSUE TITLE
Sugar code in mapping table

### ISSUE THREAD

**Issue by joshbrowning2358** [SWS-Methodology/faoswsUtil#3]
In the Datatable "fcl_2_cpc" on the SWS, we currently map FCL code 0162 to CPC code 23510.  This is incorrect, as CPC code 23510 doesn't currently exist in our CPC dimension table.  There is currently no CPC code available for this particular commodity, but it is possible one will be added soon.  Either way, the mapping table needs to be updated once more information becomes available (either by deleting this row or adjusting the CPC code).

**Comment by sebastian-c** [comment]
In the 2.1 version of CPC, it gets converted to `2351f`

**Comment by sebastian-c** [comment]
The new CPC has been implemented for this function. This issue can now be closed.
