### ISSUE TITLE
`getFBSCode` hangs on certain codes

### ISSUE THREAD

**Issue by sebastian-c** [SWS-Methodology/faoswsUtil#7]
I haven't debugged it properly but I've noticed that `getFBSCode("11")` seems to hang. I'm guessing it gets stuck in a while loop.

**Comment by joshbrowning2358** [comment]
Can you try it again?  I've added an error message to break after 10 runs so that we don't get the infinite loop problem anymore...

**Comment by sebastian-c** [comment]
Yep, that seems to fix it. Thanks Josh!
